version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn test
      - mvn surefire-report:report
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
artifacts:
  files:
    - target/calcUtil-1.0.jar